-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- environment variables

-- env = AWWW_TRANSITION_FPS,144

-- env = AWWW_TRANSITION_BEZIER,.7,.22,.3,.78

-- env = AWWW_TRANSITION_DURATION,3

-- env = AWWW_TRANSITION,center
