-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        before_sleep_cmd = "loginctl lock-session",
        after_sleep_cmd = "hyprctl dispatch dpms on",
    },
})

hl.config({
    listener = {
        timeout = 900,
        on-timeout = "loginctl lock-session",
    },
})
-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
