general {
    hide_cursor = true
    immediate_render = true
}

label {
    monitor =
    halign = center
    valign = top
    position = 0, -30
    text = $TIME12
    font_size = 25
    font_family = Monospace
}

background {
    path = ~/repos/dotfiles/wallpapers/wallhaven-ayanami.png
    blur_passes = 2
}

input-field {
    halign = center
    valign = bottom
    position = 0, 20
    outline_thickness = 2
    inner_color = rgba(100, 100, 100, 0)
    outer_color = rgba(200, 200, 200, 1)
    font_color =  rgba(200, 200, 200, 1)
    size = 200, 45
}
