-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        hide_cursor = true,
        immediate_render = true,
    },
})

hl.config({
    label = {
        halign = "center",
        valign = "top",
        position = { 0, -30 },
        text = TIME12,
        font_size = 25,
        font_family = "Monospace",
    },
})
-- NOTE: Section 'label' may be a plugin or custom section; verify the output

hl.config({
    background = {
        path = "~/repos/dotfiles/wallpapers/wallhaven-ayanami.png",
        blur_passes = 2,
    },
})
-- NOTE: Section 'background' may be a plugin or custom section; verify the output

hl.config({
    input-field = {
        halign = "center",
        valign = "bottom",
        position = { 0, 20 },
        outline_thickness = 2,
        inner_color = { "rgba(100", 100, 100, "0)" },
        outer_color = { "rgba(200", 200, 200, "1)" },
        font_color = { "rgba(200", 200, 200, "1)" },
        size = { 200, 45 },
    },
})
-- NOTE: Section 'input-field' may be a plugin or custom section; verify the output
