-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--############

--## INPUT ###

--############

-- https://wiki.hypr.land/Configuring/Variables/#input

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = {  },
        kb_model = {  },
        kb_options = {  },
        kb_rules = {  },
        follow_mouse = 1,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
            clickfinger_behavior = true,
        },
    },
})

-- See https://wiki.hypr.land/Configuring/Gestures

-- TODO: manual review: gesture = 3, "horizontal", "workspace"

-- Example per-device config

-- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})
