-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- source = binds.conf -> requires manual conversion
-- local binds = require("binds")
-- TODO: convert binds.conf to .lua and use require()

-- source = execs.conf -> requires manual conversion
-- local execs = require("execs")
-- TODO: convert execs.conf to .lua and use require()

-- source = general.conf -> requires manual conversion
-- local general = require("general")
-- TODO: convert general.conf to .lua and use require()

-- source = look.conf -> requires manual conversion
-- local look = require("look")
-- TODO: convert look.conf to .lua and use require()

-- source = input.conf -> requires manual conversion
-- local input = require("input")
-- TODO: convert input.conf to .lua and use require()

-- source = workspaces.conf -> requires manual conversion
-- local workspaces = require("workspaces")
-- TODO: convert workspaces.conf to .lua and use require()

-- source = env.conf -> requires manual conversion
-- local env = require("env")
-- TODO: convert env.conf to .lua and use require()
